services:
  - type: web
    name: qredit
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: qredit-db
          property: connectionString
      - key: APP_HOST
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "enabled"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

databases:
  - name: qredit-db
    plan: free
