default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: qredit_development

  queue:
    <<: *default
    database: qredit_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: qredit_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
